### PR TITLE
Adds applesauce as a new egg substitute [refs #5]

### PR DESCRIPTION
**Pull request by ladenedge**
This PR adds applesauce, including:

- A new cooking pot recipe using apple, sugar and water. (And dispensed with bowls.)
- A new applesauce-in-a-bowl texture.
- Applesauce tagged as egg.
- "Applesauce" included in all the current translations.

image

Thanks for your time, and all the work on this mod!

### CODE REVIEW

**Comment by ladenedge** [comment]
Additional comments:

- I was thinking it might be fun to add another apple recipe since apples are sort of underused.  Maybe caramel apple?  (Apple, soymilk and sugar?)

image

- Applesauce could also be made a liquid, like tomato sauce in Create Central Kitchen.  (Or like soymilk in your upcoming update.)  I took the liberty of making bottle and bucket textures to go with it.

image
image

Good ideas, or overkill?

**Comment by SayWhatSayMon** [comment]
Wow this is so cool! Thank you very much for making all of this. I'd love to add your applesauce to the next official update if that's ok for you. I of course will add you to the authors and credit you in the changelog. The other apple meals would be awesome in the add on I am currently working on "VeganDelight Meals".

**Comment by ladenedge** [comment]
Oh damn, sorry for the delay -- of course!  You always have consent to keep my PRs from here on out.

**Comment by SayWhatSayMon** [comment]
Don't worry I forgot to tag you. Thank you very much for your work!

**Comment by SayWhatSayMon** [comment]
Yeah the discord is active. May you send your request to me (SayWhatSayMon) again?

**Pull request merged**
